// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    return define(['backbone', 'underscore'], function(Backbone, _) {
      return root.Backbone.SM2 = factory(Backbone, _);
    });
  } else {
    return root.Backbone.SM2 = factory(root.Backbone, root._);
  }
})(this, function(Backbone, _) {
  var Player, PlayerView, QueueCursor;
  QueueCursor = (function() {

    function QueueCursor(queue) {
      this.queue = queue;
      this.ref = -1;
    }

    QueueCursor.prototype.cur = function() {
      if (_.isArray(this.ref)) {
        return this.queue[this.ref[0]][this.ref[1]];
      } else {
        return this.queue[this.ref];
      }
    };

    QueueCursor.prototype.peek = function() {
      return this.nextImpl().next;
    };

    QueueCursor.prototype.next = function() {
      var next, ref, _ref;
      _ref = this.nextImpl(), next = _ref.next, ref = _ref.ref;
      this.ref = ref;
      return next;
    };

    QueueCursor.prototype.prev = function() {
      var prev, ref, _ref;
      _ref = this.prevImpl(), prev = _ref.prev, ref = _ref.ref;
      this.ref = ref;
      return prev;
    };

    QueueCursor.prototype.prevImpl = function() {
      var prev, ref;
      if (_.isArray(this.ref)) {
        ref = _.toArray(this.ref);
        prev = this.queue[ref[0]][ref[1] - 1];
        if (prev) {
          ref[1] = ref[1] - 1;
        } else {
          prev = this.queue[ref[0] - 1];
          ref = ref[0] - 1;
        }
      } else {
        ref = this.ref - 1;
        prev = this.queue[ref];
      }
      if (_.isArray(prev)) {
        ref = [ref, prev.length - 1];
        prev = prev[prev.length - 1];
      }
      return {
        ref: ref,
        prev: prev
      };
    };

    QueueCursor.prototype.nextImpl = function() {
      var next, ref;
      if (_.isArray(this.ref)) {
        ref = _.toArray(this.ref);
        next = this.queue[ref[0]][ref[1] + 1];
        if (next) {
          ref[1] = ref[1] + 1;
        } else {
          next = this.queue[ref[0] + 1];
          ref = ref[0] + 1;
        }
      } else {
        ref = this.ref + 1;
        next = this.queue[ref];
      }
      if (_.isArray(next)) {
        ref = [ref, 0];
        next = next[0];
      }
      return {
        ref: ref,
        next: next
      };
    };

    return QueueCursor;

  })();
  Player = (function() {

    _.extend(Player.prototype, Backbone.Events);

    function Player() {
      this.sound = void 0;
      this.queue = [];
      this.cur = new QueueCursor(this.queue);
    }

    Player.prototype.add = function(playable) {
      this.queue.push(playable);
      return this.trigger('queue:add', playable);
    };

    Player.prototype.isActive = function(playable, playState) {
      var _ref, _ref1, _ref2;
      if (playState == null) {
        playState = 0;
      }
      if (playable) {
        return ((_ref = this.sound) != null ? _ref.playState : void 0) === playState && ((_ref1 = this.sound) != null ? _ref1.id : void 0) === playable.id;
      } else {
        return ((_ref2 = this.sound) != null ? _ref2.playState : void 0) === playState;
      }
    };

    Player.prototype.isPlaying = function(playable) {
      var _ref;
      return this.isActive(playable, 1) && !((_ref = this.sound) != null ? _ref.paused : void 0);
    };

    Player.prototype.isPaused = function(playable) {
      var _ref;
      return this.isActive(playable, 1) && ((_ref = this.sound) != null ? _ref.paused : void 0);
    };

    Player.prototype.play = function() {
      var playable;
      if (this.isPlaying()) {
        return;
      }
      if (this.sound != null) {
        this.sound.play();
        this.trigger('track:play', playable, this.sound);
      } else {
        playable = this.cur.next();
        if (!playable) {
          this.trigger('queue:end');
          return;
        }
        this.setPlayable(playable);
      }
      return this.sound;
    };

    Player.prototype.preloadNext = function(sound) {};

    Player.prototype.pause = function() {
      if (this.sound == null) {
        return;
      }
      this.sound.pause();
      return this.trigger('track:pause', this.sound.playable, this.sound);
    };

    Player.prototype.stop = function(destruct) {
      if (destruct == null) {
        destruct = false;
      }
      if (this.sound == null) {
        return;
      }
      this.sound.stop();
      this.trigger('track:stop', this.sound.playable, this.sound);
      if (destruct) {
        this.sound.destruct();
        return this.sound = void 0;
      }
    };

    Player.prototype.next = function() {
      if (this.sound == null) {
        return;
      }
      this.stop(true);
      this.play();
      this.trigger('queue:next', this.sound.playable, this.sound);
      return this.sound;
    };

    Player.prototype.prev = function() {
      var playable;
      if (this.sound == null) {
        return;
      }
      this.stop(true);
      playable = this.cur.prev();
      if (!playable) {
        return;
      }
      this.setPlayable(playable);
      this.trigger('queue:prev', this.sound.playable, this.sound);
      return this.sound;
    };

    Player.prototype.setPlayable = function(playable) {
      var _this = this;
      this.sound = soundManager.createSound({
        id: playable.id,
        url: _.isFunction(playable.url) ? playable.url : playable.url,
        onload: function() {
          _this.trigger('track:playStart', playable, _this.sound);
          _this.sound.play();
          return _this.preloadNext(_this.sound);
        },
        onfinish: function() {
          _this.trigger('track:finish', playable, _this.sound);
          return _this.next();
        }
      });
      this.sound.playable = playable;
      this.trigger('track:play', playable, this.sound);
      return this.sound.load();
    };

    return Player;

  })();
  PlayerView = (function(_super) {

    __extends(PlayerView, _super);

    function PlayerView() {
      return PlayerView.__super__.constructor.apply(this, arguments);
    }

    PlayerView.prototype.className = 'app';

    PlayerView.prototype.initialize = function(options) {
      this.player = (options != null ? options.player : void 0) || new Player();
      if (!(options != null ? options.disablePlayerEvents : void 0)) {
        return this.listenTo(this.player, {
          'track:play': this.onPlay,
          'track:stop': this.onStop,
          'track:pause': this.onPause,
          'queue:add queue:pop': this.onQueueChange
        });
      }
    };

    PlayerView.prototype.onPlay = function() {};

    PlayerView.prototype.onStop = function() {};

    PlayerView.prototype.onPause = function() {};

    PlayerView.prototype.onQueueChange = function() {};

    return PlayerView;

  })(Backbone.View);
  return {
    Player: Player,
    PlayerView: PlayerView
  };
});
